public enum TokenNames {
	/* terminals */
	MINUS, DIVIDE, INT, EOF, PLUS, ID, SEMICOLON, RPAREN, TIMES, LPAREN, CLASS, NIL, ARRAY,
	WHILE, EXTENDS, RETURN, NEW, IF, STRING, LBRACK, RBRACK, LBRACE, RBRACE, COMMA, DOT, ASSIGN, EQ, LT, GT,
	ERROR
}
